version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
    reviewers:
      - ronag
      - mcollina
    assignees:
      - ronag
      - mcollina
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
    reviewers:
      - ronag
      - mcollina
    assignees:
      - ronag
      - mcollina
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
