module.exports = {
  kUrl: Symbol('url'),
  kWriting: Symbol('writing'),
  kQueue: Symbol('queue'),
  kSocketTimeout: Symbol('socket timeout'),
  kRequestTimeout: Symbol('request timeout'),
  kServerName: Symbol('server name'),
  kTLSOpts: Symbol('TLS Options'),
  kClosed: Symbol('closed'),
  kReset: Symbol('reset'),
  kDestroyed: Symbol('destroyed'),
  kMaxHeadersSize: Symbol('maxHeaderSize'),
  kHeadersTimeout: Symbol('maxHeaderSize'),
  kRunningIdx: Symbol('running index'),
  kPendingIdx: Symbol('pending index'),
  kResume: Symbol('resume'),
  kError: Symbol('error'),
  kOnDestroyed: Symbol('destroy callbacks'),
  kPipelining: Symbol('pipelinig'),
  kRetryDelay: Symbol('retry delay'),
  kSocketPath: Symbol('socket path'),
  kSocket: Symbol('socket'),
  kClients: Symbol('clients'),
  kRetryTimeout: Symbol('retry timeout'),
  kEnqueue: Symbol('enqueue'),
  kMaxAbortedPayload: Symbol('max aborted payload')
}
