module.exports = {
  kUrl: Symbol('url'),
  kWriting: Symbol('writing'),
  kQueue: Symbol('queue'),
  kTimeout: Symbol('timeout'),
  kTLSOpts: Symbol('TLS Options'),
  kClosed: Symbol('closed'),
  kDestroyed: Symbol('destroyed'),
  kInflight: Symbol('inflight'),
  kComplete: Symbol('complete'),
  kError: Symbol('error'),
  kNeedDrain: Symbol('needDrain'),
  kOnDestroyed: Symbol('destroy callbacks'),
  kPipelining: Symbol('pipelinig'),
  kRetryDelay: Symbol('retry delay'),
  kSocket: Symbol('socket'),
  kParser: Symbol('parser'),
  kRetryTimeout: Symbol('retry timeout'),
  kMaxAbortedPayload: Symbol('max aborted payload')
}
