'use strict'

/**
 * @see https://developer.mozilla.org/docs/Web/HTTP/Headers
 */
const wellknownHeaderNames = /** @type {const} */ ([
  'Accept',
  'Accept-Encoding',
  'Accept-Language',
  'Accept-Ranges',
  'Access-Control-Allow-Credentials',
  'Access-Control-Allow-Headers',
  'Access-Control-Allow-Methods',
  'Access-Control-Allow-Origin',
  'Access-Control-Expose-Headers',
  'Access-Control-Max-Age',
  'Access-Control-Request-Headers',
  'Access-Control-Request-Method',
  'Age',
  'Allow',
  'Alt-Svc',
  'Alt-Used',
  'Authorization',
  'Cache-Control',
  'Clear-Site-Data',
  'Connection',
  'Content-Disposition',
  'Content-Encoding',
  'Content-Language',
  'Content-Length',
  'Content-Location',
  'Content-Range',
  'Content-Security-Policy',
  'Content-Security-Policy-Report-Only',
  'Content-Type',
  'Cookie',
  'Cross-Origin-Embedder-Policy',
  'Cross-Origin-Opener-Policy',
  'Cross-Origin-Resource-Policy',
  'Date',
  'Device-Memory',
  'Downlink',
  'ECT',
  'ETag',
  'Expect',
  'Expect-CT',
  'Expires',
  'Forwarded',
  'From',
  'Host',
  'If-Match',
  'If-Modified-Since',
  'If-None-Match',
  'If-Range',
  'If-Unmodified-Since',
  'Keep-Alive',
  'Last-Modified',
  'Link',
  'Location',
  'Max-Forwards',
  'Origin',
  'Permissions-Policy',
  'Pragma',
  'Proxy-Authenticate',
  'Proxy-Authorization',
  'RTT',
  'Range',
  'Referer',
  'Referrer-Policy',
  'Refresh',
  'Retry-After',
  'Sec-WebSocket-Accept',
  'Sec-WebSocket-Extensions',
  'Sec-WebSocket-Key',
  'Sec-WebSocket-Protocol',
  'Sec-WebSocket-Version',
  'Server',
  'Server-Timing',
  'Service-Worker-Allowed',
  'Service-Worker-Navigation-Preload',
  'Set-Cookie',
  'SourceMap',
  'Strict-Transport-Security',
  'Supports-Loading-Mode',
  'TE',
  'Timing-Allow-Origin',
  'Trailer',
  'Transfer-Encoding',
  'Upgrade',
  'Upgrade-Insecure-Requests',
  'User-Agent',
  'Vary',
  'Via',
  'WWW-Authenticate',
  'X-Content-Type-Options',
  'X-DNS-Prefetch-Control',
  'X-Frame-Options',
  'X-Permitted-Cross-Domain-Policies',
  'X-Powered-By',
  'X-Requested-With',
  'X-XSS-Protection'
])

/**
 * Lowercased response header names that stringifyHTTPHeader returns as
 * preallocated strings. Names defined by an HTTP RFC come first, then those of
 * the web platform specifications, then de facto ones common enough to be
 * worth a slot; each group is ordered by an estimate of the share of responses
 * carrying the name (HTTP Archive / Web Almanac, webtechsurvey.com, the HPACK
 * and QPACK static tables).
 *
 * stringifyHTTPHeader finds a name with a perfect hash; run
 * `node build/header-name-hash.js` after changing this list.
 */
const wellknownResponseHeaderNames = /** @type {const} */ ([
  // Defined by an RFC: HTTP semantics, caching and HTTP/1.1 (RFC 9110-9112) and
  // the RFCs for cookies, HSTS, Alt-Svc, Link, Content-Disposition,
  // X-Frame-Options, WebSocket, client hints and newer response fields.
  'date',
  'content-type',
  'server',
  'content-length',
  'cache-control',
  'last-modified',
  'etag',
  'accept-ranges',
  'expires',
  'vary',
  'connection',
  'age',
  'content-encoding',
  'strict-transport-security',
  'alt-svc',
  'via',
  'transfer-encoding',
  'x-frame-options',
  'keep-alive',
  'pragma',
  'set-cookie',
  'link',
  'upgrade',
  'location',
  'content-disposition',
  'expect-ct',
  'content-range',
  'content-language',
  'accept-ch',
  'retry-after',
  'www-authenticate',
  'cdn-cache-control',
  'cache-status',
  'allow',
  'sec-websocket-accept',
  'sec-websocket-extensions',
  'sec-websocket-protocol',
  'content-location',
  'trailer',
  'proxy-authenticate',
  'authentication-info',
  'proxy-authentication-info',
  'accept-patch',
  'preference-applied',
  'content-digest',
  'repr-digest',
  'proxy-status',
  'sunset',
  'deprecation',
  'priority',
  // Defined by the Fetch, HTML and W3C web platform specifications.
  'access-control-allow-origin',
  'x-content-type-options',
  'timing-allow-origin',
  'cross-origin-resource-policy',
  'report-to',
  'nel',
  'server-timing',
  'access-control-expose-headers',
  'content-security-policy',
  'referrer-policy',
  'access-control-allow-credentials',
  'p3p',
  'access-control-allow-methods',
  'access-control-allow-headers',
  'access-control-max-age',
  'cross-origin-opener-policy',
  'permissions-policy',
  'cross-origin-embedder-policy',
  'content-security-policy-report-only',
  'origin-agent-cluster',
  'reporting-endpoints',
  'refresh',
  'clear-site-data',
  // De facto: CDNs, object storage and common server middleware.
  'x-cache',
  'cf-ray',
  'cf-cache-status',
  'x-xss-protection',
  'x-amz-cf-pop',
  'x-amz-cf-id',
  'x-powered-by',
  'x-served-by',
  'x-cache-hits',
  'x-timer',
  'x-request-id',
  'x-amz-request-id',
  'x-amz-id-2',
  'x-robots-tag',
  'x-ua-compatible',
  'x-dns-prefetch-control',
  'x-permitted-cross-domain-policies',
  'x-download-options',
  // Common application response headers.
  'request-id',
  'x-couch-request-id',
  'x-couchdb-body-time',
  'x-elastic-product'
])

/** @type {Record<typeof wellknownHeaderNames[number]|Lowercase<typeof wellknownHeaderNames[number]>, string>} */
const headerNameLowerCasedRecord = {}

// Note: object prototypes should not be able to be referenced. e.g. `Object#hasOwnProperty`.
Object.setPrototypeOf(headerNameLowerCasedRecord, null)

for (let i = 0; i < wellknownHeaderNames.length; ++i) {
  const key = wellknownHeaderNames[i]
  const lowerCasedKey = key.toLowerCase()
  headerNameLowerCasedRecord[key] = headerNameLowerCasedRecord[lowerCasedKey] =
    lowerCasedKey
}

module.exports = {
  wellknownHeaderNames,
  wellknownResponseHeaderNames,
  headerNameLowerCasedRecord
}
