'use strict'

const { X509Certificate } = require('node:crypto')
const pem = require('@metcoder95/https-pem')

// `selfsigned` derives the certificate serial number from 9 random bytes and
// runs them through its own `toPositiveHex()`, which clears the sign bit but
// does not re-minimise the resulting DER INTEGER. Roughly 1 in 65536 serial
// numbers ends up with two redundant leading zero bytes, and node-forge's
// encoder strips only one of them, so OpenSSL refuses to load the certificate
// with ERR_OSSL_ASN1_ILLEGAL_PADDING. Every test that builds a TLS/HTTP2
// server from a freshly generated pair was flaky because of it.
//
// Each attempt draws an independent serial number, so retrying is enough:
// three attempts bring the odds down to about 1 in 2.8e14.
const ATTEMPTS = 3

async function generate (options) {
  let lastError

  for (let i = 0; i < ATTEMPTS; i++) {
    const pems = await pem.generate(options)

    try {
      new X509Certificate(pems.cert) // eslint-disable-line no-new
      return pems
    } catch (err) {
      lastError = err
    }
  }

  throw new Error(`could not generate a loadable certificate in ${ATTEMPTS} attempts`, { cause: lastError })
}

// The pair written by the package's postinstall hook is drawn from the same
// broken serial number logic, but only once per `npm run generate-pem` instead
// of once per call. There is nothing to retry here — it is generated by another
// process — so just make the failure actionable rather than let it surface as
// an `illegal padding` error from the middle of a TLS handshake.
function assertLoadable (cert) {
  if (cert != null) {
    try {
      new X509Certificate(cert) // eslint-disable-line no-new
    } catch (err) {
      throw new Error('@metcoder95/https-pem wrote a certificate OpenSSL cannot load, re-run `npm run generate-pem`', { cause: err })
    }
  }
  return cert
}

module.exports = {
  generate,
  get key () { return pem.key },
  get cert () { return assertLoadable(pem.cert) }
}
